sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
script:
  - 'npm test'
after_script:
  - 'istanbul cover --report html node_modules/.bin/_mocha tests -- -u exports -R spec && codecov'
git:
  depth: 1
