sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
script:
  - "npm run build && npm test"
after_script:
  - "istanbul cover --verbose --dir coverage node_modules/.bin/_mocha tests/tests.js -- -u exports -R spec && cat coverage/lcov.info | coveralls; rm -rf coverage/lcov*"
